# TODO: Potentially switch to cargo_xtask for easy re-targetting, i.e:
# https://github.com/card-io-ecg/card-io-fw/blob/main/Cargo.toml

[package]
name = "ssh-stamp"
version = "0.1.0"
authors = ["Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
cfg-if = "1.0.0"
ed25519-dalek = { version = "2", default-features = false }
embassy-executor = { version = "0.7", features = ["task-arena-size-40960"]}
embassy-net = { version = "0.6", features = ["tcp", "udp", "dhcpv4", "medium-ethernet"] }
smoltcp = { version = "0.12", default-features = false, features = ["medium-ethernet", "socket-raw"]}
embassy-time = { version = "0.4" }
embedded-io-async = "0.6.0"
esp-alloc = "0.7"
esp-backtrace = { version = "0.15", features = [
#    "esp32s3",
    "esp32c6",
    "exception-handler",
    "panic-handler",
    "println",
] }
# esp-hal = { version = "0.20", features = [ "esp32s3", "async" ] }
# esp-hal-embassy = { version = "0.3", features = ["esp32s3"] }
# esp-println = { version = "0.11", features = ["esp32s3", "log"] }
# esp-wifi = { version = "0.8.0", features = ["esp32s3", "wifi", "wifi-default", "utils", "smoltcp", "async", "embassy-net"] }
esp-hal = { version = "1.0.0-beta.0", features = [ "esp32c6", "unstable" ] }
esp-hal-embassy = { version = "0.7", features = ["esp32c6"] }
esp-println = { version = "0.13", features = ["esp32c6", "log"] }
esp-wifi = { version = "0.13", features = ["esp32c6", "wifi", "esp-alloc"] }
hex = { version = "0.4", default-features = false }
log = { version = "0.4" }
static_cell = { version = "2", features = ["nightly"] }
ssh-key = { version = "0.6", default-features = false, features = ["ed25519"] }
sunset = { version = "0.2.0", git="https://github.com/mkj/sunset", default-features = false, features = ["openssh-key", "embedded-io"]}
sunset-embassy = { version = "0.2.0", git = "https://github.com/mkj/sunset", default-features = false}
getrandom = { version = "0.2.10", features = ["custom"] }
embassy-sync = "0.6"
heapless = "0.8"
embassy-futures = "0.1"
edge-dhcp = "0.5"
edge-nal = "0.5"
edge-nal-embassy = "0.5"

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = 3

[profile.release]
codegen-units = 1 # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
overflow-checks = false

[features]
esp32 = []
