[package]
name = "esp-hosted-ssh"
version = "0.1.0"
authors = ["Roman Valls Guimera <brainstorm@users.noreply.github.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
ed25519-dalek = { version = "2.1.1", default-features = false }
embassy-executor = "0.6.0"
embassy-net = { version = "0.4.0", features = ["proto-ipv4", "tcp", "medium-ip"] }
embedded-io-async = "0.6.1"
esp-backtrace = { version = "0.14", features = [
    "esp32s3",
    "exception-handler",
    "panic-handler",
    "println",
] }
esp-hal = { version = "0.20", features = [ "esp32s3" ] }
esp-hal-embassy = { version = "0.3", features = ["esp32s3"] }
esp-println = { version = "0.11", features = ["esp32s3", "log"] }
hex = { version = "0.4", default-features = false }
log = { version = "0.4" }
zssh = "0.4"

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1 # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
