#[target.xtensa-esp32s3-none-elf]
[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --baud=921600 --monitor"


[env]
ESP_LOG="INFO"

[build]
rustflags = [
#  "-C", "link-arg=-nostartfiles",
  "-C", "force-frame-pointers",
]

#target = "xtensa-esp32s3-none-elf"
target = "riscv32imac-unknown-none-elf"

#[unstable]
#build-std = ["core"]
